---
- name: Create Nginx docker directory
  ansible.builtin.file:
    path: "{{ nginx_docker_path }}"
    owner: "{{ nginx_docker_owner }}"
    group: "{{ nginx_docker_group }}"
    state: directory
    mode: "0750"

- name: Create Nginx proxy configuration
  ansible.builtin.template:
    src: default.conf.j2
    dest: "{{ nginx_docker_path }}/default.conf"
    owner: "{{ nginx_docker_owner }}"
    group: "{{ nginx_docker_group }}"
    mode: "0640"
  notify: restart nginx

- name: Create Nginx TLS certificate
  ansible.builtin.copy:
    content: "{{ nginx_docker_tls_crt | ansible.builtin.mandatory }}"
    dest: "{{ nginx_docker_path }}/tls.crt"
    owner: "{{ nginx_docker_owner }}"
    group: "{{ nginx_docker_group }}"
    mode: "0640"
  notify: restart nginx

- name: Create Nginx TLS certificate key
  ansible.builtin.copy:
    content: "{{ nginx_docker_tls_key | ansible.builtin.mandatory }}"
    dest: "{{ nginx_docker_path }}/tls.key"
    owner: "{{ nginx_docker_owner }}"
    group: "{{ nginx_docker_group }}"
    mode: "0600"
  notify: restart nginx

- name: Create Nginx docker compose configuration
  ansible.builtin.template:
    src: compose.yaml.j2
    dest: "{{ nginx_docker_path }}/compose.yaml"
    owner: "{{ nginx_docker_owner }}"
    group: "{{ nginx_docker_group }}"
    mode: "0640"
  notify: restart nginx

- name: Create Nginx docker compose override configuration
  ansible.builtin.copy:
    content: "{{ nginx_docker_override | from_yaml | to_nice_yaml(indent=2) }}"
    dest: "{{ nginx_docker_path }}/compose.override.yaml"
    owner: "{{ nginx_docker_owner }}"
    group: "{{ nginx_docker_group }}"
    mode: "0640"
  when: nginx_docker_override and nginx_docker_override | length > 0
  notify: restart nginx

- name: Validate Nginx docker compose configuration
  ansible.builtin.command:
    cmd: docker compose config --quiet
    chdir: "{{ nginx_docker_path }}"
  changed_when: false

- name: Start Nginx docker compose deployment
  ansible.builtin.command:
    cmd: docker compose --ansi never --progress plain up --detach
    chdir: "{{ nginx_docker_path }}"
  register: nginx_
  changed_when: "'Started' in nginx_.stdout"
