---
- name: Create Jellyfin docker directory
  ansible.builtin.file:
    path: "{{ jellyfin_docker_path }}"
    owner: "{{ jellyfin_docker_owner }}"
    group: "{{ jellyfin_docker_group }}"
    state: directory
    mode: "0750"

- name: Create Jellyfin docker compose configuration
  ansible.builtin.template:
    src: compose.yaml.j2
    dest: "{{ jellyfin_docker_path }}/compose.yaml"
    owner: "{{ jellyfin_docker_owner }}"
    group: "{{ jellyfin_docker_group }}"
    mode: "0640"
  notify: restart jellyfin

- name: Create Jellyfin docker compose override configuration
  ansible.builtin.copy:
    content: "{{ jellyfin_docker_override | from_yaml | to_nice_yaml(indent=2) }}"
    dest: "{{ jellyfin_docker_path }}/compose.override.yaml"
    owner: "{{ jellyfin_docker_owner }}"
    group: "{{ jellyfin_docker_group }}"
    mode: "0640"
  when: jellyfin_docker_override and jellyfin_docker_override | length > 0
  notify: restart jellyfin

- name: Validate Jellyfin docker compose configuration
  ansible.builtin.command:
    cmd: docker compose config --quiet
    chdir: "{{ jellyfin_docker_path }}"
  changed_when: false

- name: Start Jellyfin docker compose deployment
  ansible.builtin.command:
    cmd: docker compose --ansi never --progress plain up --detach
    chdir: "{{ jellyfin_docker_path }}"
  register: _jellyfin
  changed_when: "'Started' in _jellyfin.stdout"
